# Generated by Django 3.0.5 on 2021-02-16 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_create', models.DateTimeField(blank=True, null=True, verbose_name='Created date')),
                ('about', models.CharField(max_length=255, null=True, verbose_name='About')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Image')),
                ('kind', models.CharField(blank=True, choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Donation', 'Donation')], max_length=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('Person', 'Person'), ('Money', 'Money'), ('Document', 'Document'), ('Phone', 'Phone'), ('Pet', 'Pet'), ('Car', 'Car'), ('Other', 'Other')], max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('city', models.CharField(max_length=255, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='Country')),
                ('street', models.CharField(max_length=255, null=True, verbose_name='Street')),
                ('postal_code', models.PositiveIntegerField(null=True, verbose_name='Postal code')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Phone number')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('photo', models.ImageField(blank=True, default='download.jpeg', null=True, upload_to='images/', verbose_name='Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='app.Post')),
                ('sharedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='app.SimpleUser')),
            ],
        ),
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='app.Post')),
                ('savedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='app.SimpleUser')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.SimpleUser'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dialog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgs', to='app.Dialog')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='app.SimpleUser')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='app.SimpleUser')),
                ('postID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.Post')),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_rcv', to='app.SimpleUser'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcv_send', to='app.SimpleUser'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='users',
            field=models.ManyToManyField(max_length=3, related_name='Dialogs', to='app.SimpleUser'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, null=True, verbose_name='Comment')),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented', to='app.SimpleUser')),
                ('postID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Post')),
            ],
        ),
    ]
