# Generated by Django 3.0.5 on 2021-02-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='post',
            name='postal_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='post',
            name='street',
            field=models.CharField(max_length=255, null=True, verbose_name='Street'),
        ),
    ]
