# Generated by Django 3.0.5 on 2021-02-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='savepost',
            unique_together={('savedby', 'postID')},
        ),
    ]
