# Generated by Django 3.0.5 on 2021-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210220_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='savepost',
            unique_together=set(),
        ),
    ]
